import type { FormatSpecV2, SourceMaterialV2 } from './types'

export const sampleSourceMaterial: SourceMaterialV2 = {
  id: 'sample-source-material',
  elements: [
    {
      id: 'background',
      role: 'background',
      priority: 'required',
      rect: { x: 0, y: 0, width: 1080, height: 1080 },
      visible: true,
      canHide: false,
      canScale: true,
      canCrop: true,
      metadata: { color: '#f4f1ea' },
    },
    {
      id: 'product-image',
      role: 'image',
      priority: 'important',
      rect: { x: 512, y: 160, width: 456, height: 640 },
      visible: true,
      minWidth: 180,
      minHeight: 180,
      canHide: false,
      canScale: true,
      canCrop: true,
      metadata: { fit: 'cover' },
    },
    {
      id: 'headline',
      role: 'headline',
      priority: 'required',
      rect: { x: 96, y: 176, width: 520, height: 216 },
      visible: true,
      text: 'Launch-ready creative that adapts to every format',
      fontSize: 72,
      minFontSize: 34,
      minWidth: 240,
      minHeight: 96,
      canHide: false,
      canScale: true,
      canCrop: false,
    },
    {
      id: 'subtitle',
      role: 'subtitle',
      priority: 'important',
      rect: { x: 96, y: 424, width: 480, height: 104 },
      visible: true,
      text: 'A compact source fixture for future candidate generation.',
      fontSize: 32,
      minFontSize: 20,
      minWidth: 220,
      minHeight: 56,
      canHide: true,
      canScale: true,
      canCrop: false,
    },
    {
      id: 'cta',
      role: 'cta',
      priority: 'optional',
      rect: { x: 96, y: 584, width: 268, height: 76 },
      visible: true,
      text: 'Try it now',
      fontSize: 28,
      minFontSize: 18,
      minWidth: 148,
      minHeight: 44,
      canHide: true,
      canScale: true,
      canCrop: false,
    },
    {
      id: 'logo',
      role: 'logo',
      priority: 'important',
      rect: { x: 96, y: 880, width: 168, height: 72 },
      visible: true,
      minWidth: 72,
      minHeight: 32,
      canHide: false,
      canScale: true,
      canCrop: false,
      metadata: { label: 'Brand mark' },
    },
  ],
  brand: {
    primaryColor: '#1f6feb',
    secondaryColor: '#ffb020',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  metadata: {
    description: 'Fixture source material for layout-engine-v2 tests.',
  },
}

export const sampleFormats: FormatSpecV2[] = [
  {
    id: 'square-1080',
    name: 'Square 1080',
    width: 1080,
    height: 1080,
    aspectRatio: 1080 / 1080,
    group: 'square',
    safeArea: { top: 64, right: 64, bottom: 64, left: 64 },
  },
  {
    id: 'vertical-1080x1920',
    name: 'Vertical 1080x1920',
    width: 1080,
    height: 1920,
    aspectRatio: 1080 / 1920,
    group: 'vertical',
    safeArea: { top: 96, right: 64, bottom: 120, left: 64 },
  },
  {
    id: 'horizontal-1200x628',
    name: 'Horizontal 1200x628',
    width: 1200,
    height: 628,
    aspectRatio: 1200 / 628,
    group: 'horizontal',
    safeArea: { top: 40, right: 56, bottom: 40, left: 56 },
  },
  {
    id: 'small-320x50',
    name: 'Small 320x50',
    width: 320,
    height: 50,
    aspectRatio: 320 / 50,
    group: 'small',
    safeArea: { top: 4, right: 8, bottom: 4, left: 8 },
  },
  {
    id: 'wide-728x90',
    name: 'Wide 728x90',
    width: 728,
    height: 90,
    aspectRatio: 728 / 90,
    group: 'wide',
    safeArea: { top: 8, right: 16, bottom: 8, left: 16 },
  },
  {
    id: 'logo-200x200',
    name: 'Logo 200x200',
    width: 200,
    height: 200,
    aspectRatio: 200 / 200,
    group: 'logo',
    safeArea: { top: 16, right: 16, bottom: 16, left: 16 },
  },
]
